project:
  type: website
  output-dir: report

execute:
  freeze: auto
  cache: false

website:
  title: "BTC scRNA Report"

  repo-url: https://github.com/break-through-cancer/btc-scrna-pipeline
  repo-branch: master
  repo-actions: [issue]

  sidebar:
    logo: SCRATCH.png
    pinned: true
    align: center

    contents:
      - auto: "notebook*.qmd"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "BTC Data Science Team"

format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    embed-resources: true
    code-fold: show
    code-tools: true
    warnings: false
    df-print: paged
    fig-format: png
    fig-dpi: 300
    fig-responsive: true
    fig-align: center
    theme: litera
  ipynb: default

format-links: [ipynb]